### PR TITLE
Add de-DE language resources

### PR DESCRIPTION
**Pull request by DocBrown101**

### CODE REVIEW

**Comment by emoacht** [comment]
Thank you for PR.
'Site' is not necessarily translated and although I am not a German speaker, is it 'Webseite'?

**Comment by DocBrown101** [comment]
Webseite or Website are both ok, but site we do not know.

**Comment by emoacht** [comment]
I see. Then how about 'License'?

**Comment by DocBrown101** [comment]
Usually it is written like this: 'Lizenz'

I wasn't sure why it wasn't translated by you. So I thought I'd translate one and not the other so we could discuss about it.

**Comment by emoacht** [comment]
IMHO, they are information on the app itself and not a part of UI which a user need to understand correctly. Most users will simply ignore them and if they click, they will easily understand what they mean. Therefore, it is not worth to spend time on thinking about their translation. Not sure what other developer think.

**Comment by DocBrown101** [comment]
Ok, then can you please remove it?

**Comment by emoacht** [comment]
Okay, working on.

**Comment by DocBrown101** [comment]
Thank you!

**Pull request merged**
